# All ubuntu-20.04 jobs should run successfully in an environment
# setup by the scripts/ci/setup/qemu/build-environment.yml task
# "Install basic packages to build QEMU on Ubuntu 18.04/20.04"

ubuntu-20.04-aarch32-all:
 needs: []
 stage: build
 tags:
 - ubuntu_20.04
 - aarch32
 rules:
 - if: '$CI_PROJECT_NAMESPACE == "qemu-project" && $CI_COMMIT_BRANCH =~ /^staging/'
   when: manual
   allow_failure: true
 - if: "$AARCH32_RUNNER_AVAILABLE"
   when: manual
   allow_failure: true
 script:
 - mkdir build
 - cd build
 - ../configure --cross-prefix=arm-linux-gnueabihf-
 - make --output-sync -j`nproc`
 - make --output-sync -j`nproc` check V=1
