# All ubuntu-24.04 jobs should run successfully in an environment
# setup by the scripts/ci/setup/ubuntu/build-environment.yml task
# "Install basic packages to build QEMU on Ubuntu 24.04"

.ubuntu_aarch64_template:
  extends: .custom_runner_template
  needs: []
  stage: build
  tags:
    - ubuntu_24.04
    - aarch64
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "qemu-project" && $CI_COMMIT_BRANCH =~ /^staging/'
    - if: '$QEMU_CI != "1" && $QEMU_CI != "2" && $CI_PROJECT_NAMESPACE != $QEMU_CI_UPSTREAM'
      when: never
    - if: '$AARCH64_RUNNER_AVAILABLE && $CI_PIPELINE_SOURCE != "schedule" && $QEMU_CI == "1"'
      when: manual
    - if: '$AARCH64_RUNNER_AVAILABLE && $CI_PIPELINE_SOURCE != "schedule"'
  before_script:
    - source scripts/ci/gitlab-ci-section
    - section_start setup "Pre-script setup"
    - JOBS=$(expr $(nproc) - 4)
    - section_end setup
  script:
    - mkdir build
    - cd build
    - section_start configure "Running configure"
    - ../configure $CONFIGURE_ARGS ||
          { cat config.log meson-logs/meson-log.txt && exit 1; }
    - section_end configure
    - section_start build "Building QEMU"
    - make --output-sync -j"$JOBS"
    - section_end build
    - section_start test "Running tests"
    - if test -n "$MAKE_CHECK_ARGS";
      then
        make -j"$JOBS" $MAKE_CHECK_ARGS ;
      fi
    - section_end test

ubuntu-24.04-aarch64-all-linux-static:
  extends: .ubuntu_aarch64_template
  variables:
    CONFIGURE_ARGS: --enable-debug --static --disable-system
    MAKE_CHECK_ARGS: check-tcg

ubuntu-24.04-aarch64-all:
  extends: .ubuntu_aarch64_template
  variables:
    MAKE_CHECK_ARGS: check
  allow_failure: true
  when: manual

ubuntu-24.04-aarch64-without-defaults:
  extends: .ubuntu_aarch64_template
  variables:
    CONFIGURE_ARGS: --disable-user --without-default-devices --without-default-features
    MAKE_CHECK_ARGS: check
  allow_failure: true
  when: manual

ubuntu-24.04-aarch64-alldbg:
  extends: .ubuntu_aarch64_template
  variables:
    CONFIGURE_ARGS: --enable-debug
    MAKE_CHECK_ARGS: check-tcg

ubuntu-24.04-aarch64-clang:
  extends: .ubuntu_aarch64_template
  variables:
    CONFIGURE_ARGS: --cc=clang --cxx=clang++ --enable-ubsan
    MAKE_CHECK_ARGS: check
  allow_failure: true
  when: manual

ubuntu-24.04-aarch64-tci:
  extends: .ubuntu_aarch64_template
  variables:
    CONFIGURE_ARGS: --enable-tcg-interpreter
    MAKE_CHECK_ARGS: check
  allow_failure: true
  when: manual

ubuntu-24.04-aarch64-notcg:
  extends: .ubuntu_aarch64_template
  variables:
    CONFIGURE_ARGS: --disable-tcg --with-devices-aarch64=minimal
    MAKE_CHECK_ARGS: check
  allow_failure: true
  when: manual
