[package]
name = "qemu_api"
version = "0.1.0"
authors = ["Manos Pitsidianakis <manos.pitsidianakis@linaro.org>"]
description = "Rust bindings for QEMU"
readme = "README.md"
resolver = "2"
publish = false

edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
qemu_api_macros = { path = "../qemu-api-macros" }
libc = "0.2.162"

[features]
default = ["debug_cell"]
allocator = []
debug_cell = []

[lints]
workspace = true
